Don't conflict with self
avahi/avahi pull request #309
Opened 2020-10-02 13:21 UTC by vladmovchan

If during registration of our own records there is an address change or address removed and re-added then `avahi-daemon` interprets its own probe as conflicting (due to presence of different or temporary non-existing address in the probe). And then it changes its name to `hostname-2` and retries.
Change of hostname without good reason could be unexpected and annoying.
To resolve this we ignore presence of non-matching records if they were sent by us.

This change resolves https://github.com/lathiat/avahi/issues/117 for me.

2021-02-26 15:45 UTC, zonque commented
I can confirm the patch in this PR fixes the problem for me on an embedded platform that operates avahi on a network bridge device. Thanks a lot for sharing!

2021-02-26 16:54 UTC, vladmovchan commented
Thank you for the feedback!

2021-03-24 15:01 UTC, ffleandro commented
What's the ETA on this?
I will try this patch to see if this fixes my observed issues.

2021-03-24 17:45 UTC, ffleandro commented
Can you provide instructions on how to test this locally in a debian installation (installed throug apt-get)?

2021-03-24 18:13 UTC, vladmovchan commented
@ffleandro, you could try to ask project author about the ETA in the original bug: https://github.com/lathiat/avahi/issues/117. Last reply from lathiat there is dated Dec 7, 2020.
And sorry I can't provide you with instructions. If you don't know how to apply patch and how to build avahi from sources I don't think you should even try. As you can put your system to a broken state from which you don't know how to rollback by yourself.

2022-09-10 09:09 UTC, SoongNoonien commented
Hi!
I'm running this patch for about two weeks now and never encountered #117 again. But I found a regression, MYHOSTNAME.local is now only reachable from the other machines in the network. Is this intended behavior?

2022-09-10 09:52 UTC, vladmovchan commented
Thank you for the feedback.
The regression which you described is not intended. I follow up if I see how to address it.

2022-10-11 19:37 UTC, pemensik commented
I think this is important fix. I have seen myself changed name of my laptop. I am pretty sure there were not another device with the same name, but my laptop were connected to two interfaces simultaneously.

2022-11-24 18:12 UTC, pemensik approved these changes
Code change seems reasonable. But I haven't tested myself whether it helps indeed.

2022-11-27 01:59 UTC, guillerodriguez commented
> Code change seems reasonable. But I haven't tested myself whether it helps indeed.

[This comment](https://github.com/lathiat/avahi/pull/309#issuecomment-1242675947) mentions a regression which is apparently acknowledged by the original author of the patch (next comment). Are you sure this change is safe?

2022-11-27 14:48 UTC, pemensik commented
No, I am not sure. I looks well in general. Thanks for pointing to a regression. Do I understand it correctly that this change should make not working this command: ``avahi-resolve -n $HOSTNAME.local`` ?

But yes, it changes the behaviour of local resolving of hostname and its reverse IPv4 address.

2022-11-27 14:54 UTC, pemensik requested changes
After aplying this change and testing it shortly, it causes different behaviour.

- ``avahi-resolve -n $HOSTNAME.local -4`` timeouts, where it succeeded before.
- ``avahi-resolve -n $HOSTNAME.local -6`` still works.
- ``avahi-resolve -a $IPV4`` timeouts, but ``avahi-resolve -a $IPV6`` with addresses from correct interface

Not sure why only IPv4 is affected and IPv6 is not. But that needs to be solved before merging.

2023-11-04 13:27 UTC, SoongNoonien commented
Hi, I may have found another regression. Mounting Samba shares using the `.local` hostname is significantly slower than without the patch. But maybe this is actually a Samba issue.

2024-07-07 14:39 UTC, evverx commented
I think this PR can be closed.

I've also opened https://github.com/avahi/avahi/issues/611 with a regression affecting local things similar to the one observed here. There was an attempt to fix similar conflicts with the reflector on and that regression was introduced in the process.

Thank you everyone for testing the patch.

2024-07-07 14:39 UTC, closed without merging